# Generated by Django 5.1 on 2024-10-10 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("signal_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserCount",
        ),
    ]
